-- Seeds 30 words per CEFR level (A1-C2), 180 total.
-- Safe to re-run: skips any word that already exists (case-insensitive).

insert into public.words (word, phonetic, meaning, level, category, example)
select v.word, v.phonetic, v.meaning, v.level, v.category, v.example
from (values
  ('hello', '/həˈloʊ/', 'Merhaba', 'A1', 'Günlük', 'Hello! How are you today?'),
  ('house', '/haʊs/', 'Ev', 'A1', 'Günlük', 'We live in a small house near the park.'),
  ('water', '/ˈwɔːtər/', 'Su', 'A1', 'Günlük', 'Can I have a glass of water, please?'),
  ('friend', '/frɛnd/', 'Arkadaş', 'A1', 'Günlük', 'She is my best friend from school.'),
  ('school', '/skuːl/', 'Okul', 'A1', 'Akademik', 'My children go to school every morning.'),
  ('family', '/ˈfæməli/', 'Aile', 'A1', 'Günlük', 'I spend the weekend with my family.'),
  ('food', '/fuːd/', 'Yemek', 'A1', 'Günlük', 'The food at this restaurant is delicious.'),
  ('happy', '/ˈhæpi/', 'Mutlu', 'A1', 'Günlük', 'She looked very happy at the party.'),
  ('book', '/bʊk/', 'Kitap', 'A1', 'Akademik', 'He is reading a new book about history.'),
  ('work', '/wɜːrk/', 'İş, çalışmak', 'A1', 'İş', 'I go to work by bus every day.'),
  ('money', '/ˈmʌni/', 'Para', 'A1', 'İş', 'We need more money to buy a new car.'),
  ('time', '/taɪm/', 'Zaman', 'A1', 'Günlük', 'I don''t have time to watch TV tonight.'),
  ('day', '/deɪ/', 'Gün', 'A1', 'Günlük', 'Today is a beautiful day.'),
  ('night', '/naɪt/', 'Gece', 'A1', 'Günlük', 'The stars are bright tonight.'),
  ('eat', '/iːt/', 'Yemek yemek', 'A1', 'Günlük', 'We usually eat dinner at seven o''clock.'),
  ('drink', '/drɪŋk/', 'İçmek', 'A1', 'Günlük', 'Would you like something to drink?'),
  ('sleep', '/sliːp/', 'Uyumak', 'A1', 'Günlük', 'I need to sleep early tonight.'),
  ('big', '/bɪɡ/', 'Büyük', 'A1', 'Günlük', 'They live in a big house in the city.'),
  ('small', '/smɔːl/', 'Küçük', 'A1', 'Günlük', 'The kitten is very small and cute.'),
  ('good', '/ɡʊd/', 'İyi', 'A1', 'Günlük', 'This is a good idea for the weekend.'),
  ('bad', '/bæd/', 'Kötü', 'A1', 'Günlük', 'The weather was bad yesterday.'),
  ('new', '/nuː/', 'Yeni', 'A1', 'Günlük', 'I bought a new phone last week.'),
  ('old', '/oʊld/', 'Eski, yaşlı', 'A1', 'Günlük', 'My grandfather is very old but healthy.'),
  ('love', '/lʌv/', 'Sevmek', 'A1', 'Günlük', 'I love spending time with my family.'),
  ('name', '/neɪm/', 'İsim', 'A1', 'Günlük', 'What is your name?'),
  ('year', '/jɪr/', 'Yıl', 'A1', 'Günlük', 'I started this job last year.'),
  ('today', '/təˈdeɪ/', 'Bugün', 'A1', 'Günlük', 'What are your plans for today?'),
  ('weather', '/ˈwɛðər/', 'Hava durumu', 'A1', 'Günlük', 'The weather is sunny today.'),
  ('car', '/kɑːr/', 'Araba', 'A1', 'Günlük', 'We travelled to the coast by car.'),
  ('shop', '/ʃɒp/', 'Dükkan, mağaza', 'A1', 'Günlük', 'There is a small shop near my house.'),
  ('journey', '/ˈdʒɜːrni/', 'Yolculuk', 'A2', 'Günlük', 'Our journey to the mountains took five hours.'),
  ('forecast', '/ˈfɔːrkæst/', 'Tahmin', 'A2', 'Günlük', 'The forecast says it will rain tomorrow.'),
  ('decide', '/dɪˈsaɪd/', 'Karar vermek', 'A2', 'Günlük', 'We need to decide where to go on holiday.'),
  ('improve', '/ɪmˈpruːv/', 'Geliştirmek', 'A2', 'Akademik', 'She wants to improve her English speaking skills.'),
  ('borrow', '/ˈbɒroʊ/', 'Ödünç almak', 'A2', 'Günlük', 'Can I borrow your pen for a minute?'),
  ('compare', '/kəmˈpɛr/', 'Karşılaştırmak', 'A2', 'Akademik', 'Let''s compare the prices before we buy.'),
  ('explain', '/ɪkˈspleɪn/', 'Açıklamak', 'A2', 'Akademik', 'Could you explain this exercise again?'),
  ('instead', '/ɪnˈstɛd/', 'Bunun yerine', 'A2', 'Günlük', 'Let''s take the bus instead of walking.'),
  ('neighbor', '/ˈneɪbər/', 'Komşu', 'A2', 'Günlük', 'Our neighbor helped us move the furniture.'),
  ('opinion', '/əˈpɪnjən/', 'Görüş, fikir', 'A2', 'Akademik', 'In my opinion, this book is excellent.'),
  ('probably', '/ˈprɒbəbli/', 'Muhtemelen', 'A2', 'Günlük', 'It will probably rain later today.'),
  ('relax', '/rɪˈlæks/', 'Rahatlamak', 'A2', 'Günlük', 'I like to relax on the beach in summer.'),
  ('remember', '/rɪˈmɛmbər/', 'Hatırlamak', 'A2', 'Günlük', 'I can''t remember where I put my keys.'),
  ('suggest', '/səˈdʒɛst/', 'Önermek', 'A2', 'İş', 'My manager suggested a new plan for the project.'),
  ('traffic', '/ˈtræfɪk/', 'Trafik', 'A2', 'Günlük', 'There was heavy traffic on the way to work.'),
  ('weekend', '/ˈwiːkɛnd/', 'Hafta sonu', 'A2', 'Günlük', 'We are going camping this weekend.'),
  ('arrive', '/əˈraɪv/', 'Varmak', 'A2', 'Günlük', 'The train will arrive at nine o''clock.'),
  ('invite', '/ɪnˈvaɪt/', 'Davet etmek', 'A2', 'Günlük', 'We invited our friends to the party.'),
  ('expensive', '/ɪkˈspɛnsɪv/', 'Pahalı', 'A2', 'İş', 'This restaurant is too expensive for us.'),
  ('cheap', '/tʃiːp/', 'Ucuz', 'A2', 'İş', 'We found a cheap hotel near the beach.'),
  ('quiet', '/ˈkwaɪət/', 'Sessiz', 'A2', 'Günlük', 'The library is always very quiet.'),
  ('crowded', '/ˈkraʊdɪd/', 'Kalabalık', 'A2', 'Günlük', 'The bus was too crowded this morning.'),
  ('comfortable', '/ˈkʌmftərbəl/', 'Rahat', 'A2', 'Günlük', 'This chair is very comfortable.'),
  ('difficult', '/ˈdɪfɪkəlt/', 'Zor', 'A2', 'Akademik', 'The exam was more difficult than expected.'),
  ('exercise', '/ˈɛksərsaɪz/', 'Egzersiz', 'A2', 'Günlük', 'I try to exercise every morning.'),
  ('healthy', '/ˈhɛlθi/', 'Sağlıklı', 'A2', 'Günlük', 'Eating vegetables is part of a healthy diet.'),
  ('holiday', '/ˈhɒlɪdeɪ/', 'Tatil', 'A2', 'Günlük', 'We are planning a holiday to Spain.'),
  ('interview', '/ˈɪntərvjuː/', 'Mülakat', 'A2', 'İş', 'She has a job interview tomorrow morning.'),
  ('polite', '/pəˈlaɪt/', 'Kibar', 'A2', 'Günlük', 'It is polite to say thank you.'),
  ('surprised', '/sərˈpraɪzd/', 'Şaşırmış', 'A2', 'Günlük', 'I was surprised to see her at the airport.'),
  ('achieve', '/əˈtʃiːv/', 'Başarmak', 'B1', 'Akademik', 'She worked hard to achieve her goals.'),
  ('advantage', '/ədˈvæntɪdʒ/', 'Avantaj', 'B1', 'İş', 'Working from home has many advantages.'),
  ('announce', '/əˈnaʊns/', 'Duyurmak', 'B1', 'İş', 'The company announced a new product today.'),
  ('appreciate', '/əˈpriːʃieɪt/', 'Takdir etmek', 'B1', 'Günlük', 'I really appreciate your help with this.'),
  ('behavior', '/bɪˈheɪvjər/', 'Davranış', 'B1', 'Akademik', 'The teacher praised the students'' good behavior.'),
  ('challenge', '/ˈtʃælɪndʒ/', 'Zorluk, meydan okuma', 'B1', 'İş', 'Learning a new language is a big challenge.'),
  ('community', '/kəˈmjuːnəti/', 'Topluluk', 'B1', 'Akademik', 'The local community organized a charity event.'),
  ('confident', '/ˈkɒnfɪdənt/', 'Kendinden emin', 'B1', 'Günlük', 'She felt confident before the exam.'),
  ('consider', '/kənˈsɪdər/', 'Göz önünde bulundurmak', 'B1', 'Akademik', 'We should consider all the options first.'),
  ('contribute', '/kənˈtrɪbjuːt/', 'Katkıda bulunmak', 'B1', 'Akademik', 'Everyone can contribute ideas to the project.'),
  ('environment', '/ɪnˈvaɪrənmənt/', 'Çevre', 'B1', 'Akademik', 'We must protect the environment for future generations.'),
  ('establish', '/ɪˈstæblɪʃ/', 'Kurmak', 'B1', 'İş', 'The company was established twenty years ago.'),
  ('increase', '/ɪnˈkriːs/', 'Artmak, artırmak', 'B1', 'İş', 'Sales increased significantly last quarter.'),
  ('involve', '/ɪnˈvɒlv/', 'İçermek, dahil etmek', 'B1', 'Akademik', 'The project involves several different departments.'),
  ('maintain', '/meɪnˈteɪn/', 'Sürdürmek, korumak', 'B1', 'İş', 'It is important to maintain a healthy lifestyle.'),
  ('negotiate', '/nɪˈɡoʊʃieɪt/', 'Müzakere etmek', 'B1', 'İş', 'They negotiated a better price for the contract.'),
  ('opportunity', '/ˌɒpərˈtuːnəti/', 'Fırsat', 'B1', 'İş', 'This job offers a great opportunity for growth.'),
  ('participate', '/pɑːrˈtɪsɪpeɪt/', 'Katılmak', 'B1', 'Akademik', 'All students are encouraged to participate in class.'),
  ('persuade', '/pərˈsweɪd/', 'İkna etmek', 'B1', 'Günlük', 'She persuaded her parents to let her travel.'),
  ('reduce', '/rɪˈdjuːs/', 'Azaltmak', 'B1', 'Akademik', 'We need to reduce our plastic waste.'),
  ('relationship', '/rɪˈleɪʃənʃɪp/', 'İlişki', 'B1', 'Günlük', 'They have a strong relationship built on trust.'),
  ('reliable', '/rɪˈlaɪəbəl/', 'Güvenilir', 'B1', 'İş', 'We need a reliable supplier for these materials.'),
  ('responsible', '/rɪˈspɒnsəbəl/', 'Sorumlu', 'B1', 'İş', 'He is responsible for managing the team.'),
  ('significant', '/sɪɡˈnɪfɪkənt/', 'Önemli', 'B1', 'Akademik', 'There has been a significant improvement in sales.'),
  ('solution', '/səˈluːʃən/', 'Çözüm', 'B1', 'Akademik', 'We found a simple solution to the problem.'),
  ('successful', '/səkˈsɛsfəl/', 'Başarılı', 'B1', 'İş', 'She built a successful career in marketing.'),
  ('surround', '/səˈraʊnd/', 'Çevrelemek', 'B1', 'Günlük', 'The house is surrounded by beautiful gardens.'),
  ('valuable', '/ˈvæljuəbəl/', 'Değerli', 'B1', 'İş', 'Her experience is very valuable to the team.'),
  ('various', '/ˈvɛriəs/', 'Çeşitli', 'B1', 'Akademik', 'The museum has various exhibitions this month.'),
  ('volunteer', '/ˌvɒlənˈtɪr/', 'Gönüllü', 'B1', 'Günlük', 'He volunteers at the animal shelter every weekend.'),
  ('accomplish', '/əˈkɒmplɪʃ/', 'Başarmak, tamamlamak', 'B2', 'İş', 'The team accomplished the project ahead of schedule.'),
  ('accurate', '/ˈækjərət/', 'Doğru, kesin', 'B2', 'Akademik', 'We need accurate data to make this decision.'),
  ('acknowledge', '/əkˈnɒlɪdʒ/', 'Kabul etmek, onaylamak', 'B2', 'Akademik', 'He acknowledged his mistake and apologized.'),
  ('adapt', '/əˈdæpt/', 'Uyum sağlamak', 'B2', 'Akademik', 'It takes time to adapt to a new culture.'),
  ('adequate', '/ˈædɪkwət/', 'Yeterli', 'B2', 'İş', 'The budget is not adequate for this project.'),
  ('anticipate', '/ænˈtɪsɪpeɪt/', 'Öngörmek, beklemek', 'B2', 'İş', 'We anticipate strong demand for the new product.'),
  ('assess', '/əˈsɛs/', 'Değerlendirmek', 'B2', 'Akademik', 'Teachers assess students'' progress every term.'),
  ('consequence', '/ˈkɒnsɪkwəns/', 'Sonuç', 'B2', 'Akademik', 'Every decision has consequences.'),
  ('constraint', '/kənˈstreɪnt/', 'Kısıtlama', 'B2', 'İş', 'Budget constraints limited what we could build.'),
  ('controversial', '/ˌkɒntrəˈvɜːrʃəl/', 'Tartışmalı', 'B2', 'Akademik', 'The new policy proved to be controversial.'),
  ('demonstrate', '/ˈdɛmənstreɪt/', 'Göstermek, kanıtlamak', 'B2', 'Akademik', 'She demonstrated how the machine works.'),
  ('diverse', '/daɪˈvɜːrs/', 'Çeşitli, farklı', 'B2', 'Akademik', 'Our team has a diverse range of skills.'),
  ('eliminate', '/ɪˈlɪmɪneɪt/', 'Ortadan kaldırmak', 'B2', 'İş', 'The new system eliminates unnecessary paperwork.'),
  ('emphasize', '/ˈɛmfəsaɪz/', 'Vurgulamak', 'B2', 'Akademik', 'The report emphasizes the need for change.'),
  ('facilitate', '/fəˈsɪlɪteɪt/', 'Kolaylaştırmak', 'B2', 'İş', 'This software facilitates communication between teams.'),
  ('feasible', '/ˈfiːzəbəl/', 'Uygulanabilir', 'B2', 'İş', 'Is it feasible to finish the project by June?'),
  ('inevitable', '/ɪnˈɛvɪtəbəl/', 'Kaçınılmaz', 'B2', 'Akademik', 'Change is inevitable in a growing company.'),
  ('innovative', '/ˈɪnəveɪtɪv/', 'Yenilikçi', 'B2', 'İş', 'The company is known for its innovative products.'),
  ('legislation', '/ˌlɛdʒɪsˈleɪʃən/', 'Mevzuat, yasa', 'B2', 'Akademik', 'New legislation was passed to protect workers.'),
  ('objective', '/əbˈdʒɛktɪv/', 'Amaç, hedef', 'B2', 'İş', 'Our main objective is to increase customer satisfaction.'),
  ('perspective', '/pərˈspɛktɪv/', 'Bakış açısı', 'B2', 'Akademik', 'It''s useful to see the issue from her perspective.'),
  ('potential', '/pəˈtɛnʃəl/', 'Potansiyel', 'B2', 'İş', 'The company has great potential for growth.'),
  ('presume', '/prɪˈzjuːm/', 'Varsaymak', 'B2', 'Akademik', 'I presume you have read the report already.'),
  ('sophisticated', '/səˈfɪstɪkeɪtɪd/', 'Karmaşık, gelişmiş', 'B2', 'Akademik', 'The device uses a sophisticated tracking system.'),
  ('sustainable', '/səˈsteɪnəbəl/', 'Sürdürülebilir', 'B2', 'Akademik', 'The city invested in sustainable energy sources.'),
  ('thorough', '/ˈθʌroʊ/', 'Kapsamlı, titiz', 'B2', 'İş', 'She did a thorough review of the contract.'),
  ('undermine', '/ˌʌndərˈmaɪn/', 'Zayıflatmak', 'B2', 'Akademik', 'The scandal undermined public trust in the government.'),
  ('versatile', '/ˈvɜːrsətaɪl/', 'Çok yönlü', 'B2', 'İş', 'He is a versatile employee who can handle many tasks.'),
  ('vulnerable', '/ˈvʌlnərəbəl/', 'Savunmasız', 'B2', 'Akademik', 'Elderly people are more vulnerable to this disease.'),
  ('widespread', '/ˈwaɪdsprɛd/', 'Yaygın', 'B2', 'Akademik', 'The use of smartphones is now widespread.'),
  ('ambiguous', '/æmˈbɪɡjuəs/', 'Belirsiz, muğlak', 'C1', 'Akademik', 'His answer was deliberately ambiguous.'),
  ('arbitrary', '/ˈɑːrbɪtrɛri/', 'Keyfi', 'C1', 'Akademik', 'The decision seemed arbitrary and unfair.'),
  ('articulate', '/ɑːrˈtɪkjəleɪt/', 'Açıkça ifade etmek', 'C1', 'Akademik', 'She articulated her concerns clearly in the meeting.'),
  ('coherent', '/koʊˈhɪrənt/', 'Tutarlı', 'C1', 'Akademik', 'The essay lacked a coherent structure.'),
  ('comprehensive', '/ˌkɒmprɪˈhɛnsɪv/', 'Kapsamlı', 'C1', 'Akademik', 'The report gives a comprehensive overview of the market.'),
  ('discrepancy', '/dɪsˈkrɛpənsi/', 'Tutarsızlık, fark', 'C1', 'Akademik', 'There was a discrepancy between the two reports.'),
  ('elaborate', '/ɪˈlæbəreɪt/', 'Ayrıntılı açıklamak', 'C1', 'Akademik', 'Could you elaborate on that last point?'),
  ('exacerbate', '/ɪɡˈzæsərbeɪt/', 'Kötüleştirmek', 'C1', 'Akademik', 'The drought exacerbated the food shortage.'),
  ('hypothesis', '/haɪˈpɒθəsɪs/', 'Hipotez, varsayım', 'C1', 'Akademik', 'The researchers tested their hypothesis in the lab.'),
  ('implicit', '/ɪmˈplɪsɪt/', 'Örtük, dolaylı', 'C1', 'Akademik', 'There was an implicit agreement between the two companies.'),
  ('inherent', '/ɪnˈhɪrənt/', 'Doğasında olan', 'C1', 'Akademik', 'The risks inherent in the investment were carefully weighed.'),
  ('mitigate', '/ˈmɪtɪɡeɪt/', 'Hafifletmek', 'C1', 'Akademik', 'The company took steps to mitigate the damage.'),
  ('notion', '/ˈnoʊʃən/', 'Kavram, fikir', 'C1', 'Akademik', 'The notion of fairness varies between cultures.'),
  ('paradox', '/ˈpærədɒks/', 'Paradoks, çelişki', 'C1', 'Akademik', 'It''s a paradox that the poorest work the hardest.'),
  ('plausible', '/ˈplɔːzəbəl/', 'Akla yatkın', 'C1', 'Akademik', 'Her explanation seemed plausible at first.'),
  ('precarious', '/prɪˈkɛriəs/', 'Kararsız, tehlikeli', 'C1', 'Akademik', 'The company is in a precarious financial position.'),
  ('prevalent', '/ˈprɛvələnt/', 'Yaygın', 'C1', 'Akademik', 'This disease is more prevalent in colder climates.'),
  ('rigorous', '/ˈrɪɡərəs/', 'Titiz, sıkı', 'C1', 'Akademik', 'The product went through rigorous testing before release.'),
  ('scrutinize', '/ˈskruːtənaɪz/', 'İnceden inceye incelemek', 'C1', 'Akademik', 'Auditors scrutinized the company''s financial records.'),
  ('subsequent', '/ˈsʌbsɪkwənt/', 'Sonraki', 'C1', 'Akademik', 'Subsequent studies confirmed the initial findings.'),
  ('substantiate', '/səbˈstænʃieɪt/', 'Kanıtlamak', 'C1', 'Akademik', 'She could not substantiate her claims with evidence.'),
  ('tangible', '/ˈtændʒəbəl/', 'Somut', 'C1', 'Akademik', 'We need tangible results, not just promises.'),
  ('underlying', '/ˌʌndərˈlaɪɪŋ/', 'Altta yatan', 'C1', 'Akademik', 'The doctor identified the underlying cause of the illness.'),
  ('unprecedented', '/ʌnˈprɛsɪdɛntɪd/', 'Eşi görülmemiş', 'C1', 'Akademik', 'The company reported unprecedented growth this year.'),
  ('viable', '/ˈvaɪəbəl/', 'Uygulanabilir, geçerli', 'C1', 'İş', 'Is this business plan financially viable?'),
  ('adverse', '/ˈædvɜːrs/', 'Olumsuz', 'C1', 'Akademik', 'The drug can have adverse side effects.'),
  ('compelling', '/kəmˈpɛlɪŋ/', 'İkna edici', 'C1', 'Akademik', 'She made a compelling argument for the change.'),
  ('discern', '/dɪˈsɜːrn/', 'Ayırt etmek, fark etmek', 'C1', 'Akademik', 'It was hard to discern the truth from the rumors.'),
  ('meticulous', '/məˈtɪkjələs/', 'Titiz, kusursuz', 'C1', 'İş', 'He is meticulous about checking every detail.'),
  ('resilient', '/rɪˈzɪljənt/', 'Dayanıklı, esnek', 'C1', 'Akademik', 'The economy proved resilient despite the crisis.'),
  ('abrogate', '/ˈæbrəɡeɪt/', 'Yürürlükten kaldırmak', 'C2', 'Akademik', 'The government moved to abrogate the old treaty.'),
  ('cacophony', '/kəˈkɒfəni/', 'Kulak tırmalayan gürültü', 'C2', 'Akademik', 'The street was filled with the cacophony of car horns.'),
  ('capricious', '/kəˈprɪʃəs/', 'Kaprisli, değişken', 'C2', 'Akademik', 'The weather in the mountains can be capricious.'),
  ('deleterious', '/ˌdɛlɪˈtɪriəs/', 'Zararlı', 'C2', 'Akademik', 'Smoking has a deleterious effect on health.'),
  ('ephemeral', '/ɪˈfɛmərəl/', 'Geçici, kısa ömürlü', 'C2', 'Akademik', 'Fame in social media can be quite ephemeral.'),
  ('equivocal', '/ɪˈkwɪvəkəl/', 'Belirsiz, iki anlamlı', 'C2', 'Akademik', 'His equivocal statement left everyone confused.'),
  ('esoteric', '/ˌɛsəˈtɛrɪk/', 'Ezoterik, az bilinen', 'C2', 'Akademik', 'The professor''s lecture was full of esoteric references.'),
  ('fastidious', '/fæˈstɪdiəs/', 'Titiz, zor beğenen', 'C2', 'Akademik', 'She is fastidious about the cleanliness of her home.'),
  ('gratuitous', '/ɡrəˈtjuːɪtəs/', 'Gereksiz, sebepsiz', 'C2', 'Akademik', 'The film was criticized for its gratuitous violence.'),
  ('iconoclast', '/aɪˈkɒnəklæst/', 'Gelenek karşıtı kişi', 'C2', 'Akademik', 'The artist was seen as an iconoclast in his era.'),
  ('incontrovertible', '/ˌɪnkɒntrəˈvɜːrtəbəl/', 'Tartışılmaz', 'C2', 'Akademik', 'The evidence was incontrovertible.'),
  ('indefatigable', '/ˌɪndɪˈfætɪɡəbəl/', 'Yorulmak bilmeyen', 'C2', 'Akademik', 'She was an indefatigable campaigner for human rights.'),
  ('juxtapose', '/ˈdʒʌkstəpoʊz/', 'Yan yana koymak', 'C2', 'Akademik', 'The exhibition juxtaposes classical and modern art.'),
  ('laconic', '/ləˈkɒnɪk/', 'Az ve öz konuşan', 'C2', 'Akademik', 'His laconic reply surprised the reporters.'),
  ('magnanimous', '/mæɡˈnænɪməs/', 'Cömert, yüce gönüllü', 'C2', 'Akademik', 'The CEO was magnanimous in victory.'),
  ('obfuscate', '/ˈɒbfʌskeɪt/', 'Karmaşık hale getirmek', 'C2', 'Akademik', 'The report seemed designed to obfuscate the real issue.'),
  ('obsequious', '/əbˈsiːkwiəs/', 'Aşırı yağcı', 'C2', 'Akademik', 'The waiter''s obsequious manner made us uncomfortable.'),
  ('paradigm', '/ˈpærədaɪm/', 'Model, paradigma', 'C2', 'Akademik', 'The discovery created a new paradigm in physics.'),
  ('perfunctory', '/pərˈfʌŋktəri/', 'Gelişigüzel, özensiz', 'C2', 'Akademik', 'He gave a perfunctory apology and left.'),
  ('pernicious', '/pərˈnɪʃəs/', 'Zararlı, yıkıcı', 'C2', 'Akademik', 'Corruption has a pernicious effect on society.'),
  ('quintessential', '/ˌkwɪntɪˈsɛnʃəl/', 'Tam anlamıyla örnek', 'C2', 'Akademik', 'Paris is the quintessential romantic city.'),
  ('recalcitrant', '/rɪˈkælsɪtrənt/', 'İnatçı, dik başlı', 'C2', 'Akademik', 'The recalcitrant committee refused to change the policy.'),
  ('sanguine', '/ˈsæŋɡwɪn/', 'İyimser', 'C2', 'Akademik', 'She remained sanguine about the company''s future.'),
  ('surreptitious', '/ˌsʌrəpˈtɪʃəs/', 'Gizli, sinsi', 'C2', 'Akademik', 'He took a surreptitious glance at his phone.'),
  ('taciturn', '/ˈtæsɪtɜːrn/', 'Az konuşan', 'C2', 'Akademik', 'The taciturn old man rarely spoke to strangers.'),
  ('ubiquitous', '/juːˈbɪkwɪtəs/', 'Her yerde bulunan', 'C2', 'Akademik', 'Smartphones have become ubiquitous in modern life.'),
  ('vacillate', '/ˈvæsɪleɪt/', 'Kararsız kalmak', 'C2', 'Akademik', 'He vacillated between the two job offers for weeks.'),
  ('veracity', '/vəˈræsəti/', 'Doğruluk', 'C2', 'Akademik', 'The journalist questioned the veracity of the claim.'),
  ('vindicate', '/ˈvɪndɪkeɪt/', 'Haklı çıkarmak', 'C2', 'Akademik', 'The new evidence vindicated her original theory.'),
  ('zealous', '/ˈzɛləs/', 'Gayretli, hevesli', 'C2', 'Akademik', 'He is a zealous supporter of environmental causes.')
) as v(word, phonetic, meaning, level, category, example)
where not exists (
  select 1 from public.words w where lower(w.word) = lower(v.word)
);
